# string manipulations test

quote = "   Test string, WITH somE strange meaNinG.    "
print("Source string:")
print(quote)
print("Upper reg:")
print(quote.upper())
print("Lower reg:")
print(quote.lower())
print("Titled:")
print(quote.title())
print("Replace:")
print(quote.replace("strange", "unpleasant"))
print("Capitalize:")
print(quote.capitalize())
print("Strip:")
print(quote.strip())
print("Swap case:")
print(quote.swapcase())
print("Is decimal:")
print(quote.isdecimal())
print("Source string:")
print(quote)
input("\n\n Press Enter to exit...")
